tasks:
  - name: AutoReload
    command: code -r /workspace/BBD_HandsON
extensions:
  - https://github.com/YKawaai/BBD_HandsON/releases/download/3.0.0/vscode-yaml-tammd-3.0.0.vsix
  - oderwat.indent-rainbow@8.2.2
  - usernamehw.errorlens@3.4.1
