tasks:
  - name: test
    command: |
      code -v
      code --install-extension mhutchie.git-graph
      code --install-extension /workspace/BBD_HandsON/vscode-yaml-tammd-3.0.0.vsix --verbose
  - name: Install Poc Extesion
    #init: code --install-extension /workspace/BBD_HandsON/vscode-yaml-tammd-3.0.0.vsix
    #before: code --install-extension /workspace/BBD_HandsON/vscode-yaml-tammd-3.0.0.vsix
    command: bash -c "code --install-extension /workspace/BBD_HandsON/vscode-yaml-tammd-3.0.0.vsix --verbose" 
vscode:
  extensions:
    #- /workspace/BBD_HandsON/vscode-yaml-tammd-3.0.0.vsix
    - oderwat.indent-rainbow@8.2.2
    - usernamehw.errorlens@3.4.1
